version: "2"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:80
    environment:
      NODE_ENV: production
version: "3.8"

services:
  uproditapplication:
    image: uproditapplication
    networks: 
      - network1
    ports:
      - "8082:8080"